### ISSUE TITLE
Dlmread error with autoalign_dynamo in matlab 

### ISSUE THREAD

**Issue by Jake4484** [alisterburt/autoalign_dynamo#1]
Hi I have been trying to work through the teamtomo.org tutorial data set and keep coming across the following error in matlab. Would you happen to have anyway around this error?

Fitter has changed its traceSet
Multilevel computing
Scanning level 1: 37 samples, interval  5.00, from -90.00 to 90.00
  ... best psi for level 1: 85.00
Scanning level 2: 5 samples, interval  2.50, from 80.00 to 90.00
  ... best psi for level 2: 85.00
Scanning level 3: 11 samples, interval  0.50, from 82.50 to 87.50
  ... best psi for level 3: 85.00
Scanning level 4: 11 samples, interval  0.10, from 84.50 to 85.50
  ... best psi for level 4: 85.20
DELETEME getUncenteredRotatedCloud
Warning: Index in position 2 exceeds array bounds (must not exceed 50). 
> In autoalign_warn (line 7)
In handle_exception (line 10)
In dautoalign4warp (line 33) 
Warning: Attempting to continue... 
> In autoalign_warn (line 7)
In handle_exception (line 11)
In dautoalign4warp (line 33) 
Error using dlmread (line 147)
Empty format character vector is not supported at the end of a file.

Error in csvread (line 48)
    m=dlmread(filename, ',', r, c);

Error in autoalign_summarise (line 5)
    m = csvread(fullfile(output_folder, 'rms.txt'));

Error in dautoalign4warp (line 36)
            autoalign_summarise(output_folder)

**Comment by alisterburt** [comment]
Hi Jake, thanks for the bug report and sorry you ran into issues

Could you confirm if you're using dynamo 1.1.522? 

This issue is actually a problem in this version of Dynamo. Here is [a temporary link](https://justbeamit.com/9qb7c) to the installer for dynamo 1.1.514 which should work for you, a fixed version of Dynamo should go live in the next day or so

**Comment by Jake4484** [comment]
Hi Alister, 

Yes this is with v-1.1.522 version of Dynamo. I'll give the dynamo version 1.1.514 a try!

**Comment by alisterburt** [comment]
let me know if you have any problems with the download! 🙂

**Comment by Jake4484** [comment]
hmm it seems I'm still getting the same error with the 1.1.514 version as well

**Comment by alisterburt** [comment]
Uh oh! Okay - given that this problem is in Dynamo rather than this package there are two ways forward

1) we wait for Daniel to upload the fixed version (this should be available in the next day or so)

2) we jump on a call this week and try to hack around it

Whichever you're more motivated for let me know, if you want to call maybe propose a few slots that work for you? I'm in the UK

**Comment by Jake4484** [comment]
I think it would make more sense to see if Daniel's fixed version works first! If it doesnt, then maybe I could give ya a call to figure this out??

**Comment by alisterburt** [comment]
Sounds good, ping me in a few days things aren't solved!

As an aside, I debugged the same error with someone else today and dropping to dynamo 1.1.514 worked in their case... not sure what's going on

**Comment by alisterburt** [comment]
dynamo 1.1.524 was just released, could you report back with whether this fixes your issue when you've had a chance to test?

**Comment by Jake4484** [comment]
Thanks! I'll install it today and give it a try! I'll keep you posted on the result!

**Comment by Jake4484** [comment]
I just downloaded it and tried it, but still get the same error there must be something strange with the setup on my end I guess?

**Comment by alisterburt** [comment]
Thanks for checking - drop me an email (alisterburt(at)gmail(dot)com) with a few times that work for you and we can organise a quick call to debug!

**Comment by alisterburt** [comment]
closing, this issue was mainly due to running on Windows, a workaround was found but it's hacky and I don't want to support windows generally 🙂

**Comment by YuX-Ren** [comment]
Hi, I have encountered the same question on desktop Ubuntu rather than Windows. Could you figure out any error regarding to this. 

cmd: 
dautoalign4warp('./imod', 1.35, 10, 85.3, './dynamo_alignments')

error log:
Output checking is active for this step.
Fitter has changed its traceSet
Attention: 35 tilts do not contain any markers.
Reference tilt moved to 15 (18.35 degres)
Multilevel computing
Scanning level 1: 37 samples, interval  5.00, from -90.00 to 90.00
  ... best psi for level 1:  0.00
Scanning level 2: 5 samples, interval  2.50, from -5.00 to  5.00
  ... best psi for level 2:  0.00
Scanning level 3: 11 samples, interval  0.50, from -2.50 to  2.50
  ... best psi for level 3:  0.00
Scanning level 4: 11 samples, interval  0.10, from -0.50 to  0.50
  ... best psi for level 4:  0.00
\------------------------------------------------------------
Entering reindexing step 1
A total of 1 different labels found in column 20 ("tomo" ):
 label number  1:   1 particles. 
[table_merge] Warning: single table remains. Merging not necessary.
Merging 1 tables  
Done merging tables
 resulting table: 1 x 35
Thinning with threshold: 20.00
 Initial number of markers   : 1
 Marker number post-thinning : 1
Multilevel computing
Scanning level 1: 37 samples, interval  5.00, from -90.00 to 90.00
  ... best psi for level 1:  0.00
Scanning level 2: 5 samples, interval  2.50, from -5.00 to  5.00
  ... best psi for level 2:  0.00
Scanning level 3: 11 samples, interval  0.50, from -2.50 to  2.50
  ... best psi for level 3:  0.00
Scanning level 4: 11 samples, interval  0.10, from -0.50 to  0.50
  ... best psi for level 4:  0.00
Warning: Dimensions of arrays being concatenated are not consistent. 
> In autoalign_warn (line 7)
In handle_exception (line 10)
In dautoalign4warp (line 32) 
Warning: Attempting to continue... 
> In autoalign_warn (line 7)
In handle_exception (line 11)
In dautoalign4warp (line 32) 
Updated RMSD stats for experimental bead positions vs. projection model
min: 0.00
max: 0.00
mean: 0.00
sdev: 0.00
No new tilt series found at 14:37:54

2 tilt series processed in this session so far
Going to sleep for 30s...
No new tilt series found at 14:38:24


Additional concerns:
The attentions says that 35 tilts do not contain any markers. In my understanding, there are 35 tilts that have no gold flucidals. However, I  am testing on the TS-01 of empair-10164, there must have multiple gold in every tilt.
