### ISSUE TITLE
Empty output files

### ISSUE THREAD

**Issue by hamid13r** [alisterburt/autoalign_dynamo#2]
Hi, I have been doing the walkthrough and after upgrading to IMOD 4.12.9 I got around the -Unbinnedpixelsize problem. There are two things I wanted to bring to your attention. First one is MATLAB has a new [argument block](https://www.mathworks.com/help/matlab/ref/arguments.html) that seems to disallow assigning a variable name as `arguments`.  

Second, I managed to run your program and it seemed to run properly as I look at the log: 
[matlab-output.txt](https://github.com/alisterburt/autoalign_dynamo/files/7367366/matlab-output.txt)
 
but the output files are empty. I can open the model file (`TS_01.mrc.mod`) without a problem but the logs and .xf files are empty. And of course, when I import them in Warp it says they are not aligned.  

`drwxrwxrwx 1 michaelscott michaelscott 4.0K Oct 18 10:12 ./

drwxrwxrwx 1 michaelscott michaelscott 4.0K Oct 18 10:12 ../
-rwxrwxrwx 1 michaelscott michaelscott  30K Oct 18 10:12 TS_01.mrc.mod*
-rwxrwxrwx 1 michaelscott michaelscott  132 Oct 18 10:12 TS_01.mrc.rawtlt*
**-rwxrwxrwx 1 michaelscott michaelscott    0 Oct 18 10:12 TS_01.mrc.tlt***
**-rwxrwxrwx 1 michaelscott michaelscott    0 Oct 18 10:12 TS_01.mrc.xf***
drwxrwxrwx 1 michaelscott michaelscott 4.0K Oct 18 10:10 info/
-rwxrwxrwx 1 michaelscott michaelscott  132 Oct 18 10:08 nominal.tlt*
**-rwxrwxrwx 1 michaelscott michaelscott    0 Oct 18 10:12 taSolution.log***
**-rwxrwxrwx 1 michaelscott michaelscott    0 Oct 18 10:12 tiltalign.stdout***
-rwxrwxrwx 1 michaelscott michaelscott  32K Oct 18 10:12 workingMarkers.dms*
**-rwxrwxrwx 1 michaelscott michaelscott    0 Oct 18 10:12 xtiltfile.xtilt***`

**Comment by alisterburt** [comment]
Hi @hamid13r ! Welcome to github and thanks for providing such a detailed description of your issue 🙂 

I think Daniel Castano-Diez (Dynamo developer) is in the process of releasing a new version of Dynamo to get around the problems with the new argument block - this issue is outside of this automatic alignment code so I won't be able to address that myself, current workarounds would be to either use an older matlab distribution (😞 ) or modify the offending functions manually/with some `grep` wizardry

This is super strange, I'm not sure why you wouldn't receive an error in the log if the call to tiltalign failed, but if it didn't fail something should appear in the `tiltalign.stdout`...

We could jump on a call sometime this week to figure out the autoalign issue, could you email me `alister` `burt` `@` `gmail` `.` `com` (joined up) with a few UK-friendly times that would work for you? It would be great if you could make sure you're zooming from a PC with access to MATLAB & your data
