### ISSUE TITLE
Issue with with autoalign

### ISSUE THREAD

**Issue by rnwokonko** [alisterburt/autoalign_dynamo#3]
Hi, I'm a new user of both Dynamo and Warp. I'm going through the #teamtomo 'Tilt series to tomograms" walkthrough and am getting hung up on the alignment step. Specifically, I am getting this error when running dautoalign4warp:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Warning: /bin/bash: point2model: command not found
 
> In check_status_cmdout (line 7)
In dms2mod (line 39)
In autoalign (line 54)
In dautoalign4warp (line 29) 
Warning: No matching files named '/Users/tutorial_data/.dynamo_alignments/TS_01.AWF/workingMarkers.mod' were found. 
> In autoalign_warn (line 7)
In handle_exception (line 10)
In dautoalign4warp (line 32) 
Warning: Attempting to continue... 
> In autoalign_warn (line 7)
In handle_exception (line 11)
In dautoalign4warp (line 32) 

I have checked to make sure that IMOD is working properly (I am using version 4.11.6), and that Dynamo and auto align are configured properly. I am getting some output files in the .dynamo_alignments directory, however when I use these in Warp, my tomograms are not being registered as Aligned.  Not sure how to trouble shoot this issue further to get it to work.

**Comment by alisterburt** [comment]
Hi @rnwokonko - welcome and thanks for the report!

Looks like there are two issues here
1. MATLAB can't see your IMOD installation. Can you try to launch matlab from a shell with IMOD sourced, or source the IMOD environment setup script from within matlab (`!source <IMOD_PATH>/IMOD-mac.sh` on my system)
2. 4.11.X versions have caused a few problems for people because some useful features added in 4.10.X beta versions were removed in 4.11.X. Would you mind updating to the [4.12.X beta versions](https://bio3d.colorado.edu/ftp/latestIMOD/) (which reintroduce those features) and retry step 1?

I'll add a note to the README now about 4.11.X. Sorry you ran into this, using an ever-evolving software stack makes things frustrating for sure 🙂 

Good luck, don't hesitate to reach out if you have any issues/questions!

**Comment by rnwokonko** [comment]
Hi @alisterburt ,
Thanks for your advice. I made both of the changes that you recommended and it seems to have fixed the issue. Many thanks!

**Comment by alisterburt** [comment]
Glad to hear it, thanks for reporting back and enjoy the processing!
